const data = {
  products: [
    {
      name: 'Nike Slim T Shirt',
      slug: 'nike-slim-T-shirt',
      category: 'T Shirts',
      image: '/image/p1.jpg',
      price: 120,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: ' high quality product',
    },
    {
      name: 'Adidas Sport Tee',
      slug: 'adidas-sport-tee',
      category: 'Sport Tee',
      image: '/image/p2.jpg',
      price: 25,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: ' high quality product',
    },
    {
      name: 'Adidas Track Pants',
      slug: 'adidas-track-pant',
      category: 'Pants',
      image: '/image/p3.jpg',
      price: 45,
      countInStock: 5,
      brand: 'Adidas',
      rating: 3.8,
      numReviews: 8,
      description: ' high quality product',
    },
    {
      name: 'Nike Soccer Pants',
      slug: 'nike-soccer-pant',
      category: 'Pants',
      image: '/image/p4.jpg',
      price: 50,
      countInStock: 25,
      brand: 'Nike',
      rating: 4.2,
      numReviews: 15,
      description: ' high quality product',
    },
  ],
};

export default data;
